[[main]]
none = "none"

[[main]]
name = "Photography"
pre = "image"
pageRef = "photography"
identifier = "gWYT9fqCDL"
weight = 3

[[main]]
name = "About Me"
pre = "mug-hot"
pageRef = "aboutme"
identifier = "BEPNUG3cOS"
weight = 1

[[main]]
name = "Publications"
pre = "file-lines"
pageRef = "publications"
identifier = "ZG1UKqswdD"
weight = 2

[[main]]
name = "Blog"
pre = "pencil"
pageRef = "blog"
identifier = "0aZ9H3AqSD"
weight = 4

[[footer]]
none = "none"

[[footer]]
name = "Instagram"
url = "https://www.instagram.com/lb.photography.gb/"
identifier = "AKjf6lZrfh"
weight = 9_999

[[footer]]
name = "Website Repository"
url = "https://github.com/DrTaboo/lbweb.uk"
identifier = "9zY0ICFQph"
weight = 9_999

[[footer]]
name = "Email Me"
url = "mailto:contactme@lbweb.uk"
identifier = "Qmzq1Pi8y9"
weight = 9_999
